services:
  - type: web
    name: todo-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: mongodb
        fromDatabase:
          name: todo-db
          property: connectionString
